Tolerance gateway
JulianGCalderon-FIUBA/distribuidos-tp1 pull request #116
Opened 2024-11-28 23:37 UTC by rplatini

2024-12-02 22:45 UTC, solmoon16 approved these changes

2024-12-03 01:29 UTC, rplatini commented on cmd/gateway/request.go
> +		err := conn.Recv(&anyMsg)
Sí, podría ser eso. Tenía la idea de usar un channel para que si el gateway ya recibió todos los resultados, notificar a esta gorutina que deje de monitorear. Pero capaz lo del error es mejor, voy a probar

2024-12-03 23:26 UTC, JulianGCalderon commented on cmd/gateway/data.go
> +	err = g.notifyFallenNode(int(g.clientCounter), middleware.CleanAll)
Aca puede haber una condicion de carrera por acceder al `clientCounter`, no?

2024-12-03 23:27 UTC, JulianGCalderon commented on cmd/gateway/request.go
> +}
Esta funcion tambien necesita un lock, para que no se actualice el contador en 2 gorutinas al mismo tiempo.

2024-12-03 23:28 UTC, JulianGCalderon commented on cmd/gateway/request.go
> +}
Creo que es imposible pero se lo agregaria por las dudas

2024-12-03 23:32 UTC, JulianGCalderon commented on cmd/gateway/data.go
> +	err = g.notifyFallenNode(int(g.clientCounter), middleware.CleanAll)
Tambien es posible que antes de esto se conecte un nuevo cliente, entonces con el `notifyFallendNode` se borren los datos del cliente que se acaba de conectar. Lo correcto seria hacer esto en la gorutina principal. En este orden:
1. Se carga el contador del archivo
2. Se envia el Clean al pipeline
3. Inician las gorutinas de requests, data, y results.
De esta forma primero se limpia toda la informacion y despues se empieza a recibir informacion nueva.

2024-12-03 23:33 UTC, JulianGCalderon requested changes
Lo probe y funciona todo OK, pero hay algunas condiciones de carrera

2024-12-03 23:34 UTC, JulianGCalderon commented on middleware/node.go
> +		}
No puede existir el cliente 0, no?

2024-12-03 23:36 UTC, JulianGCalderon commented on middleware/node.go
> +}
Hace falta este caso borde? Creo que con iterar `Keys` es suficiente, ya que si no hay keys no se envia nada.

2024-12-03 23:37 UTC, JulianGCalderon commented on scripts/compose/main.go
> +const SCORE_FILTER = 1
Podes restaurar estos cambios? Asi nos aseguramos de correr con muchos nodos en la demo

2024-12-03 23:39 UTC, JulianGCalderon commented on middleware/node.go
> +				}
Si falla en liberar los recursos, entones no se propaga por el pipeline (y tampoco se liberan los otros recursos). Creo que estaria bueno loguear un error pero continuar con la ejecucion

2024-12-03 23:39 UTC, JulianGCalderon commented on middleware/node.go
> +			}
Idem aca:
> Si falla en liberar los recursos, entones no se propaga por el pipeline (y tampoco se liberan los otros recursos). Creo que estaria bueno loguear un error pero continuar con la ejecucion

2024-12-03 23:46 UTC, JulianGCalderon commented on cmd/gateway/request.go
> +}
Idem, agregaria un lock aca por las dudas.

2024-12-04 01:55 UTC, rplatini commented on middleware/node.go
> +		}
Nop, siempre empieza desde el 1

2024-12-04 01:55 UTC, rplatini commented on middleware/node.go
> +}
Tenes razon

2024-12-04 02:15 UTC, rplatini commented on cmd/gateway/request.go
> +}
Lo puedo agregar, pero es la única gorutina (y el único lugar del sistema) donde se carga el `clientCounter`

2024-12-04 02:18 UTC, JulianGCalderon commented on cmd/gateway/request.go
> +}
Si, despues estuve viendo eso y es verdad

2024-12-04 02:19 UTC, JulianGCalderon commented on cmd/gateway/request.go
> +}
Sin lock esta bien entonces

2024-12-04 23:21 UTC, JulianGCalderon approved these changes

2024-12-04 23:21 UTC, JulianGCalderon commented on compose.yaml
Este archivo tiene unos cambios de formateo que no son generados por nuestro script, por lo que cuando ejecutamos `make write-compose` van a aparecer cambios. Podes reejecutar `write-compose`?

2024-12-04 23:24 UTC, JulianGCalderon commented on compose.yaml
Ahi lo hice yo jeje

2024-12-04 23:26 UTC, merged