Clean resources
JulianGCalderon-FIUBA/distribuidos-tp1 pull request #81
Opened 2024-10-26 02:05 UTC by rplatini

2024-10-26 13:37 UTC, JulianGCalderon reviewed
Creo que esta buena la idea, aunque me parece un poco molesto (y mas propenso a errores) tener que hacer que el handler conozca el input. Quizas podemos hacer que el `Channel` que se reciba del middleware lo guarde en un campo (antes de darselo al handler), y que con hacer `ch.Finish()` se mande el mensaje a la cola correcta

2024-10-26 13:52 UTC, JulianGCalderon reviewed
Estaria bueno probar esto con muchos clientes, y ver como evoluciona el uso de memoria con el tiempo (idealmente, deberia ser constante). 

Otra opcion mas facil es:
- levantar todos los nodos (sin levantar el cliente todavia)
- medir el uso de memoria `docker stats`
- Levantar varias clientes, esperar a que terminen:
- medir el uso de memoria otra vez, deberia ser muy similar al inicial

2024-10-26 15:46 UTC, solmoon16 reviewed
A mi también me gusta la idea, pero estoy de acuerdo con que sería más limpio que se maneje la lógica desde el middleware, y que los nodos solo hagan un finish

2024-10-26 20:16 UTC, rplatini commented on middleware/node.go
> +	qInput := slices.Collect(maps.Keys(n.config.Endpoints))[0]
Es muy poco performante esto, pero la cantidad de queues es super baja asi que no creo que afecte mucho. Si se les ocurre algo mejor, acepto

2024-10-27 01:01 UTC, JulianGCalderon commented on middleware/node.go
> +	qInput := slices.Collect(maps.Keys(n.config.Endpoints))[0]
Para evitar usar collect, solo se me ocurre usar https://pkg.go.dev/iter#Pull, igualmente no va a afectar mucho creo.

2024-10-27 01:07 UTC, JulianGCalderon commented on middleware/node.go
> +	qInput := slices.Collect(maps.Keys(n.config.Endpoints))[0]
Si nos centramos en performance, creo que hay otras cosas que tiene mas peso, por ejemplo: enviar un mensaje a rabbit y recibirlo otra vez para hacer un Finish. Probablemente haya un forma de hacerlo interno (al final del dia es el mismo nodo), aunque lo dejaria para despues.

2024-10-27 17:15 UTC, rplatini commented on middleware/node.go
> +		Fch:      fch,
le puse fch por finish channel, no me gusta mucho pero no se me ocurrio otro nombre jaja

2024-10-27 17:16 UTC, rplatini commented on middleware/node.go
> +		n.mu.Unlock()
Hay alguna forma de usar solo un lock aca?

2024-10-28 02:29 UTC, JulianGCalderon commented on middleware/node.go
> +		n.mu.Unlock()
Podrias abrir el lock antes del if, y cerrarlo despues del if, no? Una sola vez

2024-10-28 02:29 UTC, JulianGCalderon commented on middleware/node.go
> +		Fch:      fch,
Quizas es medio confuso, yo le pondria `finishCh`

2024-10-29 16:28 UTC, JulianGCalderon requested changes

2024-10-29 16:28 UTC, JulianGCalderon commented on middleware/node.go
> +
Si usas un waitgroup aca, deberias pasarle el contexto a `cleanResources`. Sino nunca terminaria. No lo probe pero creo que el graceful shutdown ya no funcionaria con esto.

2024-10-29 16:31 UTC, JulianGCalderon commented on middleware/node.go
> +
Por las dudas proba el graceful shutdown otra vez cuando lo cambies porfavor 😄

2024-10-30 04:07 UTC, JulianGCalderon approved these changes

2024-10-30 17:37 UTC, merged